name: Boomerang
version: 3.4
description: Essential commands for Chrisbot MC server.
author: Chrisbotcom
website: https://github.com/Chrisbotcom/Boomerang

main: io.github.chrisbotcom.boomerang.Boomerang
database: false

commands:
    setworldspawn:
        description: Set world spawn for new players.
        usage: /<command>
        permission: boomerang.setworldspawn
        permission-message: You don't have <permission>
    spawn:
        description: Teleport to spawn.
        usage: /<command>
    reload:
        description: Reload configurations.
        usage: /<command> [configuration]
        permission: boomerang.reload
    sethome:
        description: Set a home.
        usage: /<command> name
    delhome:
        description: Delete a home.
        usage: /<command> [name]
    home:
        description: List homes or teleport to a home if name is specified.
        usage: /<command> [name]
    tprequest:
        aliases: tpr
        description: Request to teleport to another player.
        usage: /<command> player
    tphere:
        aliases: tph
        description: Request a player to teleport to you.
        usage: /<command> player
    tpdeny:
        aliases: [tpd, tpno, tpn]
        description: Deny a teleport request from another player.
        usage: /<command> [player]
    tpaccept:
        aliases: [tpa, tpyes, tpy]
        description: Accept a teleport request from another player.
        usage: /<command> [player]
    tplist:
        aliases: tpl
        description: List pending teleport requests.
        usage: /<command>
    tpcancel:
        aliases: tpc
        description: Cancel pending teleport request.
        usage: /<command>
    mute:
        description: Mute a player in chat.
        usage: /<command> player
        permission: boomerang.mute
        permission-message: You don't have <permission>
    unmute:
        description: Unmute a player in chat or list muted players.
        usage: /<command> [player]
        permission: boomerang.mute
        permission-message: You don't have <permission>
    nightvision:
        aliases: nv
        description: Toggle night vision.
        usage: /<command>
        permission: boomerang.nightvision
        permission-message: You don't have <permission>
    fly:
        description: Toggle flight.
        usage: /<command>
        permission: boomerang.fly
        permission-message: You don't have <permission>
    info:
        description: Gets information about block looking at.
        usage: /<command>
        permission: boomerang.info
        permission-message: You don't have <permission>

# Builtin Minecraft Commands
    fill:
        description: Fills all or parts of a region with a specific block.
        usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2> <TileName> [dataValue] [oldBlockHandling] [dataTag]
        permission: boomerang.builtin
        permission-message: You don't have <permission>
    clone:
        description: Clones blocks from one region to another.
        usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2> <x> <y> <z> <maskMode> [cloneMode] [tileName]
        permission: boomerang.builtin
        permission-message: You don't have <permission>
    execute:
        description: Executes a command with a different user and position, with delegated permissions.
        usage: execute <entity> <x> <y> <z> <command …>
        permission: boomerang.builtin
        permission-message: You don't have <permission>
    particle:
        description: Creates particles.
        usage: /<command> <name> <x> <y> <z> <xd> <yd> <zd> <speed> [count] [mode]
        permission: boomerang.builtin
        permission-message: You don't have <permission>
    playsound:
        description: Plays a sound.
        usage: /<command> <sound> <player> [x] [y] [z] [volume] [pitch] [minimumVolume]
        permission: boomerang.builtin
        permission-message: You don't have <permission>
    setblock:
        description: Changes a block to another block.
        usage: /<command> <x> <y> <z> <TileName> [dataValue] [oldBlockHandling] [dataTag]
        permission: boomerang.builtin
        permission-message: You don't have <permission>

#    pos1:
#        description: Set the position of selection 1. If X, Y and Z are omitted, set the position to block standing on.
#        usage: /<command> [X Y Z]
#        permission: boomerang.pos
#        permission-message: You don't have <permission>
#
#    pos2:
#        description: Set the position of selection 2. If X, Y and Z are omitted, set the position to block standing on.
#        usage: /<command> [X Y Z]
#        permission: boomerang.pos
#        permission-message: You don't have <permission>
#
#    pos:
#        description: Show current position selection.
#        usage: /<command>
#        permission: boomerang.pos
#        permission-message: You don't have <permission>
#
#    regen:
#        description: Regenerate chunks defined by /pos selection.
#        usage: /<command>
#        permission: boomerang.regen
#        permission-message: You don't have <permission>

permissions:
    boomerang.*:
        description: Gives access to all Boomerang commands
        children:
            boomerang.setworldspawn: true
            boomerang.reload: true
    boomerang.setworldspawn:
        description: Allows you to set world spawn location.
        default: op
    boomerang.reload:
        description: Allows you to reload Boomerang settings.
        default: op
    boomerang.mute:
        description: Allows you to mute or unmute a player.
        default: op
    boomerang.nightvision:
        description: Allows you to toggle night vision.
        default: op
    boomerang.fly:
        description: Allows you to select an area.
        default: op
    boomerang.pos:
        description: Allows you to regenerate chunks defined by pos.
        default: op
    boomerang.info:
        description: Allows you to get block information.
        default: op
    boomerang.builtin:
        description: Allows access to built-in enhanced Minecraft commands.
        default: op
